### ISSUE TITLE
Asks if I want to convert .cia to .cci but then tells me it's already decrypted (but still .cia)

### ISSUE THREAD

**Issue by jacfalcon0** [rohithvishaal/3ds-converters#2]
Decrypted .cia file, run the application and it offers to convert it to .cci, I tell it yes and it says decrypting, then says it's done and check the log. I check the log and get this:

Batch CIA 3DS Decryptor Redux v1.0.3
Mon 04/15/2024 - 20:27:54 = [i] Script started
Mon 04/15/2024 - 20:28:03 = [!] CIA file "Dragon Quest VIII UncensoredOrchestrated.cia" [000400000018f100 v0] is already decrypted
Mon 04/15/2024 - 20:28:08 = [i] Decrypting process succeeded
Mon 04/15/2024 - 20:28:28 = [i] Script execution ended

I don't need to decrypt it, I need to convert it to .cci, but I still have a .cia file after. How do I get it to actually convert to .cci like it offers?

**Comment by rohithvishaal** [comment]
Hi please try this repository https://github.com/ihaveamac/3dsconv
