### ISSUE TITLE
Some files cannot be decrypted

### ISSUE THREAD

**Issue by SiriusVI87** [rohithvishaal/3ds-converters#3]
I was able to dwcrypt most .cia fils with your tool. However, the following files just cannot be converted for some reason. When launching the batch file, it will immediately say "finished", but no decrypted file is created and the log file remains empty. Any idea what's going on?

A-Train 3D (World).cia
A-Train 3D Neo (World).cia
Breakout Defense (USA).cia
Chibi Chara Koubou (World).cia
Crayon Shin-Chan Oden War (Japan).cia
Custom Monsters (World).cia
Daikaitaku Jidai - Machi o Tsukurou (World).cia
Dasshutsu Adventure - Kamikudashi no Uranai Ban (World).cia
Dasshutsu Game, The - Kiken na 5-tsu no Misshitsu (World).cia
Dasshutsu Game, The - Uragiri no Misshitsu (World).cia
Denpa Ningen RPG (World).cia
Denpa Ningen RPG 2 (World).cia
Denpa Ningen RPG 3 (World).cia
Disney Art Academy (USA).cia
Dokopon Choice Ichigo 100 Percent Color-ban Vol. 2 (Japan).cia
Dolly Kanon (World).cia
DragonFangZ - The Rose & Dungeon of Time (Japan) (New 3DS).cia
Drawing Workshop Plus (World).cia
Funassy Vs Dragons (World).cia
Gaist Crusher (World).cia
Gaist Crusher God (World).cia
Greco kara no Chousenjou! Kanji no Yakata to Obake-tachi - Shou-2 (World).cia
Greco kara no Chousenjou! Kanji no Yakata to Obake-tachi - Shou-3 (World).cia
Greco kara no Chousenjou! Kanji no Yakata to Obake-tachi - Shou-4 (World).cia
Greco kara no Chousenjou! Kanji no Yakata to Obake-tachi - Shou-5 (World).cia
Greco kara no Chousenjou! Kanji no Yakata to Obake-tachi - Shou-6 (World).cia
Gunman Story (World).cia
Kawaii Pet to Kurasou! Wan Nyan & Mini Mini Animal (World).cia
Korokesu (World).cia
LEGO Chima (World).cia
Megami Meguri (Japan) (DLC) (Alt 6).cia
Metal Max 4 - Gekkou no Diva (Japan) (DLC).cia
Minna no Oshaberi Chat (Japan) (DLC).cia
Monster Hunter 3 Tri-G (World).cia
Nintendo Presents Style Savvy - Fashion Forward (World).cia
Petite Zombies (USA).cia
Pokemon Moon (Unknown) (Debug Build).cia
Puyo Puyo Chronicle (Japan) (DLC).cia
Puyo Puyo Tetris (Japan) (DLC).cia
Shephytrial (World).cia
Simple DL Series Vol. 31 - The Misshitsu kara no Dasshutsu (Japan).cia
Sumikko Gurashi - Omise Hajimerun Desu (Japan).cia
Survivor Heroes (World).cia
Teddy Together (World).cia
Wannyandoubutsubyouin Sutekinajyuuisanninarou (World).cia
Worcle Worlds (USA).cia
Adventure Time (World).cia
Animal Crossing - Happy Home Designer (USA).cia

**Comment by rohithvishaal** [comment]
Hi please try this repository https://github.com/ihaveamac/3dsconv
